#SQLite version 3.x
#gem install sqlite3
#szsaasaz
#Ensure the SQLite 3 gem is defined in your Gemfile
#gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: localhost

production:
  <<: *default
  database: hiroyamk2_production

development:
  <<: *default
  database: hiroyamk2_development

test:
  <<: *default
  database: hiroyamk2_test