#SQLite version 3.x
#gem install sqlite3
#szsaasaz
#Ensure the SQLite 3 gem is defined in your Gemfile
#gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: 127.0.0.1
  socket: /tmp/mysql.sock
​
development:
  <<: *default
  database: jaminpo_development
​
test:
  <<: *default
  database: jaminpo_test
​
production:
  <<: *default
  database: jaminpo_production
 